[book]
authors = ["zhufengning"]
language = "zh-cn"
multilingual = false
src = "src"
title = "NEX game文档站"
[preprocessor.toc]
command = "./mdbook-toc"
renderer = ["html"]
marker = "[toc]"
[output.html]
git-repository-url = "https://github.com/zhufengning/nexgame-docs"