[book]
authors = ["zhufengning"]
language = "zh-cn"
multilingual = false
src = "src"
title = "NEX 文档站"
[preprocessor.toc]
command = "./mdbook-toc"
renderer = ["html"]
marker = "[toc]"
[preprocessor.katex]
command = "./mdbook-katex"
after = ["links"]
[output.html]
git-repository-url = "https://github.com/zhufengning/nexgame-docs/"
edit-url-template = "https://github.com/zhufengning/nexgame-docs/edit/main/{path}"
no-section-label = true

[output.html.fold]
enable = true
evel = 1

